name: Test on IKS.

on:
  workflow_dispatch: # manual run

# environment variables available to all jobs in this workflow
env:
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-south
  IKS_CLUSTER: iter8

jobs:
  # Test quickstart
  test-quickstart-on-iks:
    name: Test quickstart on IKS cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service
        ibmcloud plugin install -f container-registry
    - name: Authenticate with IBM Cloud CLI
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g default
    - name: Set kubectl context
      run: |
        ibmcloud ks cluster config --cluster $IKS_CLUSTER
        kubectl config current-context
    - name: Install KFServing with Istio
      run:
        git clone --branch v0.4.1 https://github.com/kubeflow/kfserving.git
        cd kfserving
        eval ./hack/quick_install.sh
    - name: Install knative-monitoring
      run: |
        kubectl create ns knative-monitoring
        kubectl apply -f https://github.com/knative/serving/releases/download/v0.18.0/monitoring-metrics-prometheus.yaml
